#! /bin/sh

#Autostart
sxhkd &
picom &
greenclip daemon &
wal -i ~/Pictures/Wallpapers &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &

#variable
alias bc='bspc config'
alias br='bspc rule'

#Workspaces
bspc monitor -d 1 2 3 4 5

#Others
bc border_width 0
bc window_gap 10
bc split_ratio 0.50
bc borderless_monocle true
bc gapless_monocle false
bc focus_follows_pointer true

#rules
br -a feh state=floating
br -a sxiv state=floating
br -a mpv state=floating
br -a firefox desktop='^2' follow=on
